<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>lf</string>
	</array>
	<key>name</key>
	<string>Lingua Franka</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(port)\s*(.+?)\s</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.port.lf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.portname.lf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Port definition</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>meta.port.lf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>(entry|exit|barrier|--&gt;|&lt;-|-&gt;)</string>
			<key>name</key>
			<string>keyword.other.lf</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(action)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.function.lf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Action definition, without script body</string>
			<key>end</key>
			<string>(?=@\{)</string>
			<key>name</key>
			<string>meta.action.lf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(parameterType|resultType)\s*(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.type.lf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.lf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Type definition</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.lf</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.type.lf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(clientData)\s*(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.type.lf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.lf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Clientdata</string>
			<key>end</key>
			<string>\}\n</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.lf</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.clientdata.lf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#contextMenu</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(where)\s*(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.where.lf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.lf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Parameter value definition</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.lf</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.where.lf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameter</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>State identifier</string>
			<key>match</key>
			<string>[a-zA-Z0-9]{2,}</string>
			<key>name</key>
			<string>constant.language.state.lf</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>@\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.lf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Lua scripts</string>
			<key>end</key>
			<string>\}@</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.lf</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.script.lf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#script</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.lf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Code block</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.lf</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.block.lf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>contextMenu</key>
		<dict>
			<key>begin</key>
			<string>(\"context_menu\").*(@\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.lf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.lf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}@</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.lf</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.clientdata.contextMenu.lf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<key>expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#script</string>
				</dict>
			</array>
		</dict>
		<key>parameter</key>
		<dict>
			<key>begin</key>
			<string>(.*?)\s*:</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.lf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>script</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(parameter|result|service|operation|call|event|result|error|status)</string>
					<key>name</key>
					<string>variable.language.lf</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lua</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Double quoted string literals</string>
					<key>match</key>
					<string>\".*?\"</string>
					<key>name</key>
					<string>string.quoted.double.lf</string>
				</dict>
			</array>
		</dict>
		<key>type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.lf</string>
	<key>uuid</key>
	<string>138d7a37-da91-4258-a6bb-baf600a79eb7</string>
</dict>
</plist>
