<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>lf</string>
	</array>
	<key>name</key>
	<string>Lingua Franka</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#parameter</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#normalState</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#link</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>barrier</key>
		<dict>
			<key>begin</key>
			<string>(barrier)\s*([_a-zA-Z][_a-zA-Z0-9]*)\s*{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.barrier.lf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.barrier.lf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Barrier</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.barrier.lf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.target.lf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(-&gt;)\s*([_a-zA-Z][_a-zA-Z0-9]*)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>builtin</key>
		<dict>
			<key>comment</key>
			<string>Built-in functions and variables</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.lf</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Built-in functions</string>
					<key>match</key>
					<string>\b(service|event|operation|child|port)\s*\(</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Built-in variables</string>
					<key>match</key>
					<string>\b(?:parent|parameter|result|variable)\b</string>
					<key>name</key>
					<string>support.variable.lf</string>
				</dict>
			</array>
		</dict>
		<key>clientData</key>
		<dict>
			<key>begin</key>
			<string>^\s*(clientData)\s*{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.clientdata.lf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Client data blocks</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#image</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#contextMenu</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#description</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>comment</key>
			<string>Single-line comments</string>
			<key>match</key>
			<string>--.*$</string>
			<key>name</key>
			<string>comment.line.double-dash</string>
		</dict>
		<key>contextMenu</key>
		<dict>
			<key>begin</key>
			<string>contextMenu\s*:\s+@{</string>
			<key>comment</key>
			<string>Embedded HTML in context menus</string>
			<key>contentName</key>
			<string>meta.embedded.block.html</string>
			<key>end</key>
			<string>}@;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)(viewmodel)(&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.metadata.script.start.html</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.html</string>
						</dict>
						<key>3 </key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Highlighting for &lt;viewmodel&gt; (does not support attributes)</string>
					<key>contentName</key>
					<string>source.js</string>
					<key>end</key>
					<string>(&lt;/)(viewmodel)(&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.metadata.script.end.html</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<key>description</key>
		<dict>
			<key>begin</key>
			<string>description\s*:\s+@{</string>
			<key>comment</key>
			<string>Embedded Markdown in description blocks</string>
			<key>contentName</key>
			<string>meta.embedded.block.markdown</string>
			<key>end</key>
			<string>}@;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.markdown#inline</string>
				</dict>
			</array>
		</dict>
		<key>expression</key>
		<dict>
			<key>comment</key>
			<string>Expression in port/action condition or where block</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#builtin</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>comment</key>
					<string>Nesting</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>image</key>
		<dict>
			<key>begin</key>
			<string>image\s*:\s+@{</string>
			<key>comment</key>
			<string>Embedded SVG in image blocks</string>
			<key>contentName</key>
			<string>meta.embedded.block.html</string>
			<key>end</key>
			<string>}@;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<key>link</key>
		<dict>
			<key>begin</key>
			<string>([_a-zA-Z][_a-zA-Z0-9]*)\s*(&lt;-)\s*([_a-zA-Z][_a-zA-Z0-9]*)\s*{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.link.lf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.link.lf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.lf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Link</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#clientData</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#portDeclaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>literal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>comment</key>
					<string>Single-line string literals, e.g. "Error: \"collision\""</string>
					<key>end</key>
					<string>"</string>
					<key>includes</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.lf</string>
						</dict>
					</array>
					<key>name</key>
					<string>string.quoted.double.lf</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Boolean literals</string>
					<key>match</key>
					<string>\b(?:true|false)\b</string>
					<key>name</key>
					<string>constant.language.lf</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Nil literal</string>
					<key>match</key>
					<string>\b(?:nil)\b</string>
					<key>name</key>
					<string>constant.language.lf</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Float literals, e.g. 0.2</string>
					<key>match</key>
					<string>\b\d?\\.\d+\b</string>
					<key>name</key>
					<string>constant.numeric.lf</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Integer literals, e.g. 123</string>
					<key>match</key>
					<string>\b\d+\b</string>
					<key>name</key>
					<string>constant.numeric.lf</string>
				</dict>
			</array>
		</dict>
		<key>lua</key>
		<dict>
			<key>comment</key>
			<string>Embedded Lua in action, entry, exit blocks</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Entry/exit keywords</string>
					<key>match</key>
					<string>^\s*(entry|exit|action)</string>
					<key>name</key>
					<string>keyword.other.lua.lf</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>@{</string>
					<key>comment</key>
					<string>Multi-line Lua blocks</string>
					<key>contentName</key>
					<string>meta.embedded.block.lua</string>
					<key>end</key>
					<string>}@</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.lua</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=entry|exit)\s*"</string>
					<key>comment</key>
					<string>Single-line entry/exit Lua strings</string>
					<key>contentName</key>
					<string>meta.embedded.inline.lua</string>
					<key>end</key>
					<string>$|"</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.lua</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>normalState</key>
		<dict>
			<key>begin</key>
			<string>([_a-zA-Z][_a-zA-Z0-9]*)\s*{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.state.lf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Normal state</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#clientData</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#portDefinition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#typeDeclaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lua</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#state</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>operator</key>
		<dict>
			<key>comment</key>
			<string>Boolean and arithmetic operators</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.lf</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Space-separated operators</string>
					<key>match</key>
					<string>(?&lt;=\s)(==|~=|&lt;=?|&gt;=?|and|or|not)(?=\s)</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Inline operators</string>
					<key>match</key>
					<string>\+|-|\*|\/|#</string>
					<key>name</key>
					<string>keyword.operator.lf</string>
				</dict>
			</array>
		</dict>
		<key>parameter</key>
		<dict>
			<key>comment</key>
			<string>Parameter definitions ("where" blocks)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(where)\s*{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.parameter.lf</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Multi-line where block</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(where)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.parameter.lf</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Single-line where expression</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>portDeclaration</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.port.lf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.port.lf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.port.lf</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.target.lf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Port declaration (without condition) and required connection</string>
			<key>match</key>
			<string>^\s*(port)\s+([_a-zA-Z][_a-zA-Z0-9]*)\s*(-&gt;)\s*([_a-zA-Z][_a-zA-Z0-9]*)</string>
		</dict>
		<key>portDefinition</key>
		<dict>
			<key>comment</key>
			<string>Port definition (with condition) and optional connection</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.port.lf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.port.lf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(port)\s+([_a-zA-Z][_a-zA-Z0-9]*)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.port.lf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.target.lf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(-&gt;)\s*([_a-zA-Z][_a-zA-Z0-9]*)</string>
				</dict>
			</array>
		</dict>
		<key>state</key>
		<dict>
			<key>comment</key>
			<string>State, barrier, or link</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.start-state.lf</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Start state arrow</string>
					<key>match</key>
					<string>(--&gt;)(?=.*{)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameter</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#normalState</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#barrier</string>
				</dict>
			</array>
		</dict>
		<key>type</key>
		<dict>
			<key>comment</key>
			<string>Struct, array, and primitive types</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>comment</key>
					<string>Struct</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.lf</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Fixed/variable length array</string>
					<key>match</key>
					<string>\[(\d+)\]</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Primitive type</string>
					<key>match</key>
					<string>\b(int|string|float|bool)\b</string>
					<key>name</key>
					<string>support.type.lf</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>typeDeclaration</key>
		<dict>
			<key>comment</key>
			<string>Parameter/result/variable types</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(parameterType|resultType|variableType)\s*{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.type.lf</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Bracket-delimited type declarations</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(parameterType|resultType|variableType)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.type.lf</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Single-line type declarations</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.lf</string>
	<key>uuid</key>
	<string>138d7a37-da91-4258-a6bb-baf600a79eb7</string>
</dict>
</plist>
